description: Sops secret
options:
  - name: secret_name
    description: Local secret name
    regex: "^[a-zA-Z][a-zA-Z_0-9]{0,32}$"
filenames_replace:
  - regex: "^secret_name"
    replace_var_name: "secret_name"
help_message: | 
  #######################################################################
  # cluster.dev sops secret template (https://github.com/mozilla/sops)  #
  # cdev console tool generator                                         #
  #######################################################################
  
  To create and use the SOPS secret:
  1) export the necessary data to encrypt the key with SOPS (SOPS_KMS_ARN, SOPS_PGP_FP, AZURE_* or VAULT_*, see details here: https://github.com/mozilla/sops#usage)
  2) All data in `encrypted_data` category will be encrypted and available for use in the stacks configs.
  3) To use this secret in the stack config use go-template reference: {{ .secret.secret_name.username }} or {{ .secret.secret_name.password }}
  