# action.yml
name: 'Create/Update K8s Cluster'
description: 'Create or Update Kubernetes Cluster'
inputs:
  cluster-config:  # id of input
    description: 'Path for cluster config/s file or directory'
    required: true
    default: '.cluster.dev'
  cloud-user:
    description: 'Cloud username or ID'
    required: true
  cloud-pass:
    description: 'Cloud password or secret key'
    required: true
outputs:
  status: # id of output
    description: 'An status for the job'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cluster-config }}
    - ${{ inputs.cloud-user }}
    - ${{ inputs.cloud-pass }}
branding:
    icon: 'server'
    color: 'green'
