description: AWS Secret Manager
options:
  - name: secret_name
    description: Local secret name
    regex: "^[a-zA-Z][a-zA-Z_0-9]{0,32}$"
  - name: region
    description: AWS region
    regex: "^[a-zA-Z][a-zA-Z0-9_\\-]{0,32}$"
  - name: aws_secret_name
    description: Name of secret in AWS Secrets manager (you should create it)
    regex: "^[a-zA-Z][a-zA-Z_0-9]{0,64}$"
filenames_replace:
  - regex: "^secret_name"
    replace_var_name: secret_name
help_message: | 
  ###############################################################################
  # AWS Secret Manager cluster.dev secret example.                              #
  # cdev console tool generator                                                 #
  ###############################################################################
  To create and use the AWS secret:                                           
  1) export your AWS access keys or AWS_PROFILE. See details here: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html   
  2) use aws cli to crete secret: aws --region "us-east-1" secretsmanager create-secret --name "my_aws_secret" --secret-string '{"username":"bob"},{"password":"abc123xyz456"}'
  3) To use this secret in the stack config use go-template reference: {{ .secret.secret_name.username }}. 
  See usage examples in generated secret's comments.
  
