# Example on how to install public helm chart using public values
# with redefinition on some values inside application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 4.0.0
    chart: filebeat
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: config.filebeat.config.modules.reload.enabled
          value: 'true'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
