name: pre-commit

on:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ~0.12
    - uses: lablabs/setup-terraform-docs@v1
      name: Setup Terraform docs
      with:
        terraform_docs_version: v0.10.1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: pre-commit/action@v2.0.0
      env:
        SKIP: no-commit-to-branch
